apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta3
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
nodes:
# Control-plane нода
- role: control-plane
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
  - containerPort: 30008
    hostPort: 30008
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

# Worker-ноди для MySQL
- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
  labels:
    app: mysql
  taints:
    - key: "app"
      value: "mysql"
      effect: "NoSchedule"

- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
  labels:
    app: mysql
  taints:
    - key: "app"
      value: "mysql"
      effect: "NoSchedule"

# Worker-ноди для TodoApp
- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
  labels:
    app: todoapp

- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
  labels:
    app: todoapp

- role: worker
  extraMounts:
    - hostPath: /tmp
      containerPath: /data
  labels:
    app: todoapp
